run: *.java
	javac -cp .:jars/json-20240303.jar:jars/Java-WebSocket-1.5.7.jar:jars/slf4j-api-2.0.6.jar *.java
	java -cp .:jars/json-20240303.jar:jars/Java-WebSocket-1.5.7.jar:jars/slf4j-api-2.0.6.jar Server

comp: *.java
	javac -cp .:jars/json-20240303.jar:jars/Java-WebSocket-1.5.7.jar:jars/slf4j-api-2.0.6.jar *.java